version: '3'

services:
  cricket:
    image: nginx:alpine
    container_name: cricket
    ports:
      - "8081:80"
    volumes:
      - ./cricket:/usr/share/nginx/html:ro

  football:
    image: nginx:alpine
    container_name: football
    ports:
      - "8082:80"
    volumes:
      - ./football:/usr/share/nginx/html:ro

  volleyball:
    image: nginx:alpine
    container_name: volleyball
    ports:
      - "8083:80"
    volumes:
      - ./volleyball:/usr/share/nginx/html:ro
